# Generated by Django 4.0.3 on 2022-06-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
