# Generated by Django 4.0.3 on 2022-06-29 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_epic', '0002_post_class_subtitle_alter_post_class_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_class',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
